name: gesture
description: flutter 你画我猜小游戏  作者梁典典
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  web_socket_channel: ^2.2.0
  dd_taoke_sdk: ^1.6.1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  extended_image: ^6.2.1
  fbroadcast_nullsafety: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/