name: gesture
description: flutter 你画我猜小游戏  作者梁典典
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  cupertino_icons: ^1.0.3
  web_socket_channel: ^2.1.0
  dd_taoke_sdk: ^1.5.1
  hive: ^2.0.4
  hive_flutter: any
  extended_image: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/